export const initialCards = [
  {
    name: "Человек-паук",
    country: "",
    director: "",
    duration: "",
    year: "2002",
    description: "",
    image: "https://i.ytimg.com/vi/oCM7hVG3M-s/maxresdefault.jpg",
    trailerLink: "",
    tumbnail: "",
    owner: "",
    movieId: "",
    nameRU: "",
    nameEN: "",
    _id: "1",
  },
  {
    name: "Человек-паук 2",
    country: "",
    director: "",
    duration: "",
    year: "2004",
    description: "",
    image: "https://i.ytimg.com/vi/nrDXgIcwEEI/maxresdefault.jpg",
    trailerLink: "",
    tumbnail: "",
    owner: "",
    movieId: "",
    nameRU: "",
    nameEN: "",
    _id: "2",
  },
  {
    name: "Человек-паук 3: Враг в отражении",
    country: "",
    director: "",
    duration: "",
    year: "2007",
    description: "",
    image: "https://img.rl0.ru/afisha/e904x508p0x0f1890x1080q85i/s1.afisha.ru/mediastorage/f9/c1/a08aabb27a304a54a78bd49dc1f9.jpg",
    trailerLink: "",
    tumbnail: "",
    owner: "",
    movieId: "",
    nameRU: "",
    nameEN: "",
    _id: "3",
  },
  {
    name: "Новый Человек-паук",
    country: "",
    director: "",
    duration: "",
    year: "2012",
    description: "",
    image: "https://f.vividscreen.info/soft/6dfb9b75bc41955762141650bc089586/The-Amazing-Spider-Man-800x600.jpg",
    trailerLink: "",
    tumbnail: "",
    owner: "",
    movieId: "",
    nameRU: "",
    nameEN: "",
    _id: "4",
  },
  {
    name: "Новый Человек-паук: Высокое напряжение",
    country: "",
    director: "",
    duration: "",
    year: "2014",
    description: "",
    image: "https://www.film.ru/sites/default/files/styles/epsa_1024x450/public/trailers_frame/the-amazing-spider-man-2-movie_0.jpg",
    trailerLink: "",
    tumbnail: "",
    owner: "",
    movieId: "",
    nameRU: "",
    nameEN: "",
    _id: "5",
  },
  {
    name: "Человек-паук: Возвращение домой",
    country: "",
    director: "",
    duration: "",
    year: "2017",
    description: "",
    image: "https://a-static.besthdwallpaper.com/spider-man-homecoming-movie-spiderman-and-ironman-in-action-wallpaper-800x600-15603_17.jpg",
    trailerLink: "",
    tumbnail: "",
    owner: "",
    movieId: "",
    nameRU: "",
    nameEN: "",
    _id: "6",
  },
  {
    name: "Человек-паук: Через вселенные",
    country: "",
    director: "",
    duration: "",
    year: "2018",
    description: "",
    image: "https://i.playground.ru/p/XUgrRqaKfipUzHGdMmbiIA.png",
    trailerLink: "",
    tumbnail: "",
    owner: "",
    movieId: "",
    nameRU: "",
    nameEN: "",
    _id: "7",
  },
  {
    name: "Человек-паук: Вдали от дома",
    country: "",
    director: "",
    duration: "",
    year: "2019",
    description: "",
    image: "https://avatars.mds.yandex.net/get-kinopoisk-post-img/1345014/7bf987af4c64675839161ed0d57e5c16/960x540",
    trailerLink: "",
    tumbnail: "",
    owner: "",
    movieId: "",
    nameRU: "",
    nameEN: "",
    _id: "8",
  },
  {
    name: "Человек-паук: Нет пути домой",
    country: "",
    director: "",
    duration: "",
    year: "2021",
    description: "",
    image: "https://99px.ru/sstorage/53/2022/01/tmb_338696_174073.jpg",
    trailerLink: "",
    tumbnail: "",
    owner: "",
    movieId: "",
    nameRU: "",
    nameEN: "",
    _id: "9",
  },
];

export const MainOptions = {
  url: "https://api.super.movies.nomoredomains.club",
  headers: {
    "Content-Type": "application/json",
  },
};

export const MoviesOptions = {
  url: "https://api.nomoreparties.co/",
}

export const ShortDuration = 40;

export const resolutions = {
  laptopL: 1280,
  laptop: 1200,
  tablet: 776,

}

export const maxCardNumber = {
  laptopLMaxCards: 12,
  laptopMaxCards: 9,
  tabletMaxCards: 8,
  mobileDeviceMaxCards: 5,
}